// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/form/button.vue')['default']
    DataGrid: typeof import('./src/components/DataGrid.vue')['default']
    FormButton: typeof import('./src/components/form/FormButton.vue')['default']
    FormCalendar: typeof import('./src/components/form/FormCalendar.vue')['default']
    FormDate: typeof import('./src/components/form/FormDate.vue')['default']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    FormSelect: typeof import('./src/components/form/FormSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
